# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/sargo/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),sargo)

$(call add-radio-file-sha1-checked,radio/abl.img,3ba44323c99bf37d2cdc92bbbcb945f1b776f376)
$(call add-radio-file-sha1-checked,radio/aop.img,704047ad6c485774a2e789c2b42cfc8e37601777)
$(call add-radio-file-sha1-checked,radio/cmnlib.img,17f4fe394096f049bd004f7d624b987515bbb288)
$(call add-radio-file-sha1-checked,radio/cmnlib64.img,1f827fbe7d2754fe74a18975e078f0a9e57a5454)
$(call add-radio-file-sha1-checked,radio/devcfg.img,b92e2507761ce1bf45922af38ac639d2af92cd60)
$(call add-radio-file-sha1-checked,radio/hyp.img,ea150b1580bb0d57f100003241a0ad6e7948d6e8)
$(call add-radio-file-sha1-checked,radio/keymaster.img,589709a5be75804e3229844b114d3ebb278368fa)
$(call add-radio-file-sha1-checked,radio/modem.img,2672f5718224aebb0d8185ac714ddd3b2cd3af59)
$(call add-radio-file-sha1-checked,radio/qupfw.img,bb4fbfbcdcdee177829b66979e4114ed093ec51a)
$(call add-radio-file-sha1-checked,radio/tz.img,33b64261a98f7f65a75858114b846c05cfa312c4)
$(call add-radio-file-sha1-checked,radio/xbl.img,6f9fcaf9c9fe3e610d33bd94419229814eb84742)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,2fcf02bcc1d9ad31ace5ef0755bc5c34ca23b8a4)

endif
