# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/sargo/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    abl \
    aop \
    cmnlib \
    cmnlib64 \
    devcfg \
    hyp \
    keymaster \
    modem \
    qupfw \
    tz \
    xbl \
    xbl_config
